name: Deployment in an EC2 Machine

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v4
        
      - name: Looking into the Runner Machine
        run: ls && cat /etc/os-release

      - name: Execute SSH into EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            whoami
            ls -l
            cat /etc /os-release
            sudo apt update
            sudo apt install nginx -y
            sudo mkdir /var/www/html
            sudo chown -R ${{ secrets.EC2_SSH_KEY }} /var/www/html
            sudo chmod -R 755 /var/www/html

      - name: Sending Files Over SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: /var/www/html/

      - name: Restarting Nginx Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo systemctl status nginx
            ls -l /var/www/html/
            sudo systemctl restart nginx