name: Deployment in an EC2 Machine

on:
  push:
    branches:
      - github_actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Code
        uses: actions/checkout@v4
        
      - name: Looking into the Runner Machine
        run: ls && cat /etc/os-release

      - name: Execute SSH into EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $ {{ secrets.EC2_HOST }}
          username: $ {{ secrets.EC2_USER }}
          key: $ {{ secrets.EC2_SSH_KEY }}
          port: 22
          script: whoami
